version: '3.9'

services:
  postgres14_storage2:
    image: postgres:14
    container_name: postgres14_storage2
    ports:
      - "5432:5432"
    #jdbc:postgres14_storage2://localhost:5432/storage2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0
      POSTGRES_DB: storage2
    volumes:
      - "postgres14_storage2_data:/var/lib/postgresql/data"

volumes:
  postgres14_storage2_data:
