server:
  port: ${PORT:8088}
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/storage2}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:0}
  jpa:
    #   create
    generate-ddl: false
    #    show
    show-sql: false
    properties:
      hibernate:
        #        show
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    #   create
    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      indent_output: true


